name: google_mobile_ads_adapter
description: An adapter package for the google_mobile_ads plugin, designed to simplify ads integration and management.
version: 1.1.1
repository: https://github.com/Xeertz-Org/google_mobile_ads_adapter.git

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
      sdk: flutter
  google_mobile_ads: ^6.0.0
  logging: ^1.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  lints: ^5.1.1
  test: ^1.26.2
  mocktail: ^1.0.4
